# Generated by Django 3.0.4 on 2020-04-18 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autoapp_tingg', '0002_jsonsimulator'),
    ]

    operations = [
        migrations.CreateModel(
            name='MockingData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('1', 'Active'), ('2', 'In-active')], default='2', max_length=2)),
                ('unique_name', models.CharField(max_length=10, unique=True)),
                ('json_string', models.TextField()),
                ('description', models.TextField()),
            ],
        ),
    ]
