# Generated by Django 3.0.4 on 2020-06-16 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autoapp_tingg', '0003_mockingdata'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestrailDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('1', 'Active'), ('2', 'In-active')], default='2', max_length=2)),
                ('testrail_name', models.CharField(max_length=200)),
                ('testrail_password', models.CharField(max_length=200)),
                ('testrail_url', models.URLField()),
            ],
            options={
                'verbose_name': 'TestRail',
                'verbose_name_plural': 'TestRail Settings',
                'db_table': 'TestRail',
            },
        ),
    ]
