# Generated by Django 3.0.7 on 2020-07-07 10:13

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('autoapp_tingg', '0006_auto_20200617_1405'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apisettings',
            name='port',
        ),
        migrations.RemoveField(
            model_name='environmentports',
            name='port',
        ),
        migrations.AddField(
            model_name='apisettings',
            name='environment',
            field=models.CharField(default=django.utils.timezone.now, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='apisettings',
            name='status',
            field=models.CharField(choices=[('1', 'Active'), ('2', 'In-active')], default='2', max_length=2),
        ),
        migrations.AlterField(
            model_name='apisettings',
            name='unique_name',
            field=models.CharField(max_length=50),
        ),
    ]
