# Generated by Django 3.0.7 on 2020-07-08 07:07

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('autoapp_tingg', '0007_auto_20200707_1013'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uisettings',
            name='encoded_url',
        ),
        migrations.AddField(
            model_name='uisettings',
            name='environment',
            field=models.CharField(default=django.utils.timezone.now, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='uisettings',
            name='path',
            field=models.CharField(default=django.utils.timezone.now, max_length=20),
            preserve_default=False,
        ),
    ]
