# Generated by Django 3.0.7 on 2020-07-08 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autoapp_tingg', '0009_auto_20200708_0722'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EnvironmentPorts',
        ),
        migrations.AlterModelOptions(
            name='jsonsimulator',
            options={'verbose_name': 'JSONSimulator', 'verbose_name_plural': 'JSONSimulators'},
        ),
        migrations.AddField(
            model_name='jsonsimulator',
            name='environment',
            field=models.CharField(default='hello', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='jsonsimulator',
            name='path',
            field=models.CharField(default=None, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='jsonsimulator',
            name='status',
            field=models.CharField(choices=[('1', 'Active'), ('2', 'In-active')], default='2', max_length=2),
        ),
        migrations.AlterModelTable(
            name='jsonsimulator',
            table='JSONSimulator',
        ),
    ]
