# Generated by Django 2.2.2 on 2019-07-30 13:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('autoapp_mula', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='apisettings',
            options={'verbose_name': 'Endpoint', 'verbose_name_plural': 'Endpoints'},
        ),
        migrations.AlterModelTable(
            name='apisettings',
            table='APISettings',
        ),
    ]
