# Generated by Django 2.2.2 on 2019-09-10 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autoapp_mula', '0002_auto_20190730_1335'),
    ]

    operations = [
        migrations.CreateModel(
            name='Acknowledge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('1', 'Accept'), ('2', 'Reject')], default='2', max_length=2)),
                ('status_code', models.CharField(max_length=3)),
                ('description', models.TextField()),
            ],
            options={
                'verbose_name': 'ACK',
                'verbose_name_plural': 'ACK Settings',
                'db_table': 'ACKSettings',
            },
        ),
    ]
