# Generated by Django 2.2.2 on 2019-09-11 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autoapp_mula', '0007_auto_20190911_0820'),
    ]

    operations = [
        migrations.AlterField(
            model_name='environmentports',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='uisettings',
            name='description',
            field=models.TextField(),
        ),
    ]
