# Generated by Django 2.2.2 on 2019-09-11 08:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('autoapp_mula', '0008_auto_20190911_0822'),
    ]

    operations = [
        migrations.RenameField(
            model_name='apisettings',
            old_name='encoded_url',
            new_name='path',
        ),
    ]
