# Generated by Django 2.2.2 on 2019-09-11 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autoapp_mula', '0009_auto_20190911_0846'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apisettings',
            name='unique_name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
