# Generated by Django 2.2.2 on 2019-09-11 09:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('autoapp_mula', '0010_auto_20190911_0854'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Acknowledge',
            new_name='WebHook',
        ),
        migrations.AlterModelOptions(
            name='webhook',
            options={'verbose_name': 'WebHook', 'verbose_name_plural': 'WebHooks'},
        ),
        migrations.AlterModelTable(
            name='webhook',
            table='WebHookSettings',
        ),
    ]
