# Generated by Django 2.2.2 on 2019-09-11 09:54

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('autoapp_mula', '0011_auto_20190911_0951'),
    ]

    operations = [
        migrations.AddField(
            model_name='webhook',
            name='url',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
    ]
