# Generated by Django 2.2.2 on 2019-09-16 14:37

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('autoapp_mula', '0013_auto_20190911_1132'),
    ]

    operations = [
        migrations.AddField(
            model_name='webhook',
            name='fail_url',
            field=models.URLField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='webhook',
            name='success_url',
            field=models.URLField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
