# Generated by Django 2.2.2 on 2019-09-16 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autoapp_mula', '0014_auto_20190916_1437'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apisettings',
            name='path',
            field=models.URLField(),
        ),
        migrations.AlterField(
            model_name='apisettings',
            name='url',
            field=models.URLField(),
        ),
        migrations.AlterField(
            model_name='uisettings',
            name='encoded_url',
            field=models.URLField(),
        ),
        migrations.AlterField(
            model_name='uisettings',
            name='url',
            field=models.URLField(),
        ),
        migrations.AlterField(
            model_name='webhook',
            name='status_code',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='webhook',
            name='url',
            field=models.URLField(),
        ),
    ]
