# Generated by Django 2.2.2 on 2019-09-16 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autoapp_mula', '0015_auto_20190916_1440'),
    ]

    operations = [
        migrations.AlterField(
            model_name='webhook',
            name='status_code',
            field=models.BigIntegerField(),
        ),
    ]
