# Generated by Django 2.2.2 on 2019-09-16 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autoapp_mula', '0016_auto_20190916_1442'),
    ]

    operations = [
        migrations.AlterField(
            model_name='webhook',
            name='status_code',
            field=models.CharField(max_length=3),
        ),
    ]
