# Generated by Django 2.2.2 on 2019-09-18 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autoapp_mula', '0018_auto_20190916_1446'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uisettings',
            name='display_name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='uisettings',
            name='unique_name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
