# Generated by Django 2.2.6 on 2019-10-03 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autoapp_mula', '0019_auto_20190918_0809'),
    ]

    operations = [
        migrations.AddField(
            model_name='apisettings',
            name='port',
            field=models.IntegerField(default=123),
            preserve_default=False,
        ),
    ]
